load("//bazel:api.bzl", "modular_py_library", "mojo_shared_library")

package(default_visibility = ["//visibility:public"])

mojo_shared_library(
    name = "token",
    srcs = ["token.mojo"],
    shared_lib_name = "token.so",
    deps = [
        "@mojo//:std",
    ],
)

mojo_shared_library(
    name = "grammar",
    srcs = [
        "grammar.mojo",
        # Actually a dep, revisit
        "token.mojo",
    ],
    shared_lib_name = "grammar.so",
    tags = ["manual"],
    deps = [
        "@mojo//:std",
    ],
)

modular_py_library(
    name = "token_lib",
    data = [
        ":grammar",
        ":token",
    ],
    imports = ["../.."],
    pyi_srcs = glob(["*.pyi"]),
)

filegroup(
    name = "srcs",
    srcs = glob(["*.py"]),
)
